# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartS"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartS_flat_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(5.2721, -12.7279, 0)
	P002 = App.Vector(18.0000, -18.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(65.0316, -23.7567, 0)
	P004 = App.Vector(109.2864, -40.6869, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(114.3151, -39.6097, 0)
	P006 = App.Vector(114.1267, -34.4704, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(89.1296, -9.4736, 0)
	P008 = App.Vector(61.7370, 12.8723, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(51.4379, 18.1726, 0)
	P010 = App.Vector(40.0000, 20.0000, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(23.3749, 18.0643, 0)
	P012 = App.Vector(7.6393, 12.3607, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.0640, 7.2654, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa0():
	FC000 = ctr_face_myPartS_flat_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa1_Ctr0():
	P000 = App.Vector(0.0000, -95.0000, 0)
	P001 = App.Vector(2.6433, -108.3906, 0)
	P002 = App.Vector(13.9810, -115.9901, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(59.8692, -130.3346, 0)
	P004 = App.Vector(101.7511, -153.9437, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(107.0154, -153.3914, 0)
	P006 = App.Vector(107.1225, -148.0993, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(82.2112, -120.8081, 0)
	P008 = App.Vector(55.3472, -95.4367, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(46.4614, -89.4964, 0)
	P010 = App.Vector(36.3438, -86.0501, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(22.1251, -84.7958, 0)
	P012 = App.Vector(7.9747, -86.6693, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.7766, -89.6756, 0)
	P014 = App.Vector(0.0000, -95.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa1():
	FC000 = ctr_face_myPartS_flat_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa2_Ctr0():
	P000 = App.Vector(0.0000, -190.0000, 0)
	P001 = App.Vector(-0.0393, -203.5214, 0)
	P002 = App.Vector(9.4939, -213.1103, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(53.6674, -236.7277, 0)
	P004 = App.Vector(92.5620, -268.2916, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(97.9192, -268.5197, 0)
	P006 = App.Vector(98.6899, -263.2133, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(75.9955, -231.5008, 0)
	P008 = App.Vector(51.3923, -201.2454, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(43.6097, -194.1127, 0)
	P010 = App.Vector(34.4016, -188.9497, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.6957, -185.1709, 0)
	P012 = App.Vector(8.4781, -184.1643, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.3805, -185.8348, 0)
	P014 = App.Vector(0.0000, -190.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa2():
	FC000 = ctr_face_myPartS_flat_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa3_Ctr0():
	P000 = App.Vector(0.0000, -285.0000, 0)
	P001 = App.Vector(-2.6703, -298.1250, 0)
	P002 = App.Vector(4.7223, -309.2940, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(46.1491, -343.0333, 0)
	P004 = App.Vector(80.8607, -383.6488, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(86.1608, -384.7760, 0)
	P006 = App.Vector(87.7212, -379.5869, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(68.5064, -342.6648, 0)
	P008 = App.Vector(47.2686, -306.8681, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(40.2723, -297.9790, 0)
	P010 = App.Vector(31.5980, -290.7180, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.5887, -284.8484, 0)
	P012 = App.Vector(8.6075, -281.3691, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.7638, -281.9045, 0)
	P014 = App.Vector(0.0000, -285.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa3():
	FC000 = ctr_face_myPartS_flat_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa4_Ctr0():
	P000 = App.Vector(0.0000, -380.0000, 0)
	P001 = App.Vector(-5.1480, -392.2268, 0)
	P002 = App.Vector(-0.1426, -404.5126, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(36.9118, -449.2522, 0)
	P004 = App.Vector(65.5739, -499.7809, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(70.6284, -501.8615, 0)
	P006 = App.Vector(73.0397, -496.9562, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(58.8731, -454.5569, 0)
	P008 = App.Vector(42.4252, -412.9895, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(36.1918, -401.5210, 0)
	P010 = App.Vector(27.9267, -391.4180, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.8138, -383.8901, 0)
	P012 = App.Vector(8.3784, -378.3388, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.9396, -377.9105, 0)
	P014 = App.Vector(0.0000, -380.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa4():
	FC000 = ctr_face_myPartS_flat_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa5_Ctr0():
	P000 = App.Vector(0.0000, -475.0000, 0)
	P001 = App.Vector(-7.3788, -485.8711, 0)
	P002 = App.Vector(-4.9093, -498.7758, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(25.4693, -555.2019, 0)
	P004 = App.Vector(45.5110, -616.0714, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(50.1103, -619.0962, 0)
	P006 = App.Vector(53.3748, -614.6640, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(46.0757, -567.0795, 0)
	P008 = App.Vector(36.1075, -519.9818, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(31.0759, -504.9501, 0)
	P010 = App.Vector(23.5387, -491.0053, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(16.4714, -482.2611, 0)
	P012 = App.Vector(7.8369, -475.0602, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.9276, -473.8406, 0)
	P014 = App.Vector(0.0000, -475.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa5():
	FC000 = ctr_face_myPartS_flat_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_flat():
	FA000 = face_myPartS_flat_Fa0()
	FA001 = face_myPartS_flat_Fa1()
	FA002 = face_myPartS_flat_Fa2()
	FA003 = face_myPartS_flat_Fa3()
	FA004 = face_myPartS_flat_Fa4()
	FA005 = face_myPartS_flat_Fa5()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(5.2721, -12.7279, 0)
	P002 = App.Vector(18.0000, -18.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(65.0316, -23.7567, 0)
	P004 = App.Vector(109.2864, -40.6869, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(114.3151, -39.6097, 0)
	P006 = App.Vector(114.1267, -34.4704, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(89.1296, -9.4736, 0)
	P008 = App.Vector(61.7370, 12.8723, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(51.4379, 18.1726, 0)
	P010 = App.Vector(40.0000, 20.0000, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(23.3749, 18.0643, 0)
	P012 = App.Vector(7.6393, 12.3607, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.0640, 7.2654, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf00_Fa0():
	FC000 = ctr_face_myPartS_prf00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf00():
	FA000 = face_myPartS_prf00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(2.6433, -13.3906, 0)
	P002 = App.Vector(13.9810, -20.9901, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(59.8692, -35.3346, 0)
	P004 = App.Vector(101.7511, -58.9437, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(107.0154, -58.3914, 0)
	P006 = App.Vector(107.1225, -53.0993, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(82.2112, -25.8081, 0)
	P008 = App.Vector(55.3472, -0.4367, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(46.4614, 5.5036, 0)
	P010 = App.Vector(36.3438, 8.9499, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(22.1251, 10.2042, 0)
	P012 = App.Vector(7.9747, 8.3307, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.7766, 5.3244, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf01_Fa0():
	FC000 = ctr_face_myPartS_prf01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf01():
	FA000 = face_myPartS_prf01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-0.0393, -13.5214, 0)
	P002 = App.Vector(9.4939, -23.1103, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(53.6674, -46.7277, 0)
	P004 = App.Vector(92.5620, -78.2916, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(97.9192, -78.5197, 0)
	P006 = App.Vector(98.6899, -73.2133, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(75.9955, -41.5008, 0)
	P008 = App.Vector(51.3923, -11.2454, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(43.6097, -4.1127, 0)
	P010 = App.Vector(34.4016, 1.0503, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.6957, 4.8291, 0)
	P012 = App.Vector(8.4781, 5.8357, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.3805, 4.1652, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf02_Fa0():
	FC000 = ctr_face_myPartS_prf02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf02():
	FA000 = face_myPartS_prf02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-2.6703, -13.1250, 0)
	P002 = App.Vector(4.7223, -24.2940, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(46.1491, -58.0333, 0)
	P004 = App.Vector(80.8607, -98.6488, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(86.1608, -99.7760, 0)
	P006 = App.Vector(87.7212, -94.5869, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(68.5064, -57.6648, 0)
	P008 = App.Vector(47.2686, -21.8681, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(40.2723, -12.9790, 0)
	P010 = App.Vector(31.5980, -5.7180, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.5887, 0.1516, 0)
	P012 = App.Vector(8.6075, 3.6309, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.7638, 3.0955, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf03_Fa0():
	FC000 = ctr_face_myPartS_prf03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf03():
	FA000 = face_myPartS_prf03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf04_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-5.1480, -12.2268, 0)
	P002 = App.Vector(-0.1426, -24.5126, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(36.9118, -69.2522, 0)
	P004 = App.Vector(65.5739, -119.7809, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(70.6284, -121.8615, 0)
	P006 = App.Vector(73.0397, -116.9562, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(58.8731, -74.5569, 0)
	P008 = App.Vector(42.4252, -32.9895, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(36.1918, -21.5210, 0)
	P010 = App.Vector(27.9267, -11.4180, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.8138, -3.8901, 0)
	P012 = App.Vector(8.3784, 1.6612, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.9396, 2.0895, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf04_Fa0():
	FC000 = ctr_face_myPartS_prf04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf04():
	FA000 = face_myPartS_prf04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf05_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-7.3788, -10.8711, 0)
	P002 = App.Vector(-4.9093, -23.7758, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(25.4693, -80.2019, 0)
	P004 = App.Vector(45.5110, -141.0714, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(50.1103, -144.0962, 0)
	P006 = App.Vector(53.3748, -139.6640, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(46.0757, -92.0795, 0)
	P008 = App.Vector(36.1075, -44.9818, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(31.0759, -29.9501, 0)
	P010 = App.Vector(23.5387, -16.0053, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(16.4714, -7.2611, 0)
	P012 = App.Vector(7.8369, -0.0602, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3.9276, 1.1594, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf05_Fa0():
	FC000 = ctr_face_myPartS_prf05_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf05():
	FA000 = face_myPartS_prf05_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartS_prf00():
	FIG = myPartS_prf00()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartS_prf00 = fex_subpax_myPartS_prf00()

def fex_subpax_myPartS_prf01():
	FIG = myPartS_prf01()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_myPartS_prf01 = fex_subpax_myPartS_prf01()

def fex_subpax_myPartS_prf02():
	FIG = myPartS_prf02()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 40.0000))
	return VFP
subpax_myPartS_prf02 = fex_subpax_myPartS_prf02()

def fex_subpax_myPartS_prf03():
	FIG = myPartS_prf03()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 60.0000))
	return VFP
subpax_myPartS_prf03 = fex_subpax_myPartS_prf03()

def fex_subpax_myPartS_prf04():
	FIG = myPartS_prf04()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 80.0000))
	return VFP
subpax_myPartS_prf04 = fex_subpax_myPartS_prf04()

def fex_subpax_myPartS_prf05():
	FIG = myPartS_prf05()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 100.0000))
	return VFP
subpax_myPartS_prf05 = fex_subpax_myPartS_prf05()

def fvol_pax_myPartS():
	V000 = subpax_myPartS_prf00
	V001 = V000.fuse(subpax_myPartS_prf01)
	V002 = V001.fuse(subpax_myPartS_prf02)
	V003 = V002.fuse(subpax_myPartS_prf03)
	V004 = V003.fuse(subpax_myPartS_prf04)
	V005 = V004.fuse(subpax_myPartS_prf05)
	VFC = V005.removeSplitter()
	return VFC
pax_myPartS = fvol_pax_myPartS()


pax_myPartS.check()
#pax_myPartS.exportBrep(f"{outFileName}.brep")
#pax_myPartS.exportIges(f"{outFileName}.igs")
#pax_myPartS.exportStep(f"{outFileName}.stp")
pax_myPartS.exportStl(f"{outFileName}.stl")

