# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartE"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartE_faceCartesian_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(20.0000, 20.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 40.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(40.0000, 40.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(50.0000, 20.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(60.0000, 40.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(70.0000, 40.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(80.0000, 20.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(90.0000, 40.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(100.0000, 40.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(110.0000, 20.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(120.0000, 40.0000, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(130.0000, 40.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(140.0000, 20.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(150.0000, 40.0000, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(160.0000, 40.0000, 0)
	S016 = Part.LineSegment(P016, P017)
	P018 = App.Vector(170.0000, 20.0000, 0)
	S017 = Part.LineSegment(P017, P018)
	P019 = App.Vector(180.0000, 40.0000, 0)
	S018 = Part.LineSegment(P018, P019)
	P020 = App.Vector(190.0000, 40.0000, 0)
	S019 = Part.LineSegment(P019, P020)
	P021 = App.Vector(200.0000, 20.0000, 0)
	S020 = Part.LineSegment(P020, P021)
	P022 = App.Vector(210.0000, 40.0000, 0)
	S021 = Part.LineSegment(P021, P022)
	P023 = App.Vector(220.0000, 40.0000, 0)
	S022 = Part.LineSegment(P022, P023)
	P024 = App.Vector(230.0000, 20.0000, 0)
	S023 = Part.LineSegment(P023, P024)
	P025 = App.Vector(240.0000, 40.0000, 0)
	S024 = Part.LineSegment(P024, P025)
	P026 = App.Vector(250.0000, 40.0000, 0)
	S025 = Part.LineSegment(P025, P026)
	P027 = App.Vector(250.0000, 0.0000, 0)
	S026 = Part.LineSegment(P026, P027)
	P028 = App.Vector(0.0000, 0.0000, 0)
	S027 = Part.LineSegment(P027, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartE_faceCartesian_Fa0():
	FC000 = ctr_face_myPartE_faceCartesian_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartE_faceCartesian():
	FA000 = face_myPartE_faceCartesian_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartE_facePolarAbs_Fa0_Ctr0():
	P000 = App.Vector(20.0000, 0.0000, 0)
	P001 = App.Vector(28.2843, 28.2843, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(14.1421, 14.1421, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 20.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-28.2843, 28.2843, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-14.1421, 14.1421, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-40.0000, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-20.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-28.2843, -28.2843, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-14.1421, -14.1421, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-0.0000, -40.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(-0.0000, -20.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(28.2843, -28.2843, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(14.1421, -14.1421, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(40.0000, 0.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(20.0000, 0.0000, 0)
	S015 = Part.LineSegment(P015, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartE_facePolarAbs_Fa0():
	FC000 = ctr_face_myPartE_facePolarAbs_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartE_facePolarAbs():
	FA000 = face_myPartE_facePolarAbs_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartE_facePolarRel_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(10.0000, 17.3205, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.3209, 30.1763, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(44.1147, 37.0167, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(64.1147, 37.0167, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(82.9086, 30.1763, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(98.2295, 17.3205, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(108.2295, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartE_facePolarRel_Fa0():
	FC000 = ctr_face_myPartE_facePolarRel_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartE_facePolarRel():
	FA000 = face_myPartE_facePolarRel_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartE_cartesian():
	FIG = myPartE_faceCartesian()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartE_cartesian = fex_subpax_myPartE_cartesian()

def fex_subpax_myPartE_polarAbs():
	FIG = myPartE_facePolarAbs()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 100.0000))
	return VFP
subpax_myPartE_polarAbs = fex_subpax_myPartE_polarAbs()

def fex_subpax_myPartE_polarRel():
	FIG = myPartE_facePolarRel()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 200.0000))
	return VFP
subpax_myPartE_polarRel = fex_subpax_myPartE_polarRel()

def fvol_pax_myPartE():
	V000 = subpax_myPartE_cartesian
	V001 = V000.fuse(subpax_myPartE_polarAbs)
	V002 = V001.fuse(subpax_myPartE_polarRel)
	VFC = V002.removeSplitter()
	return VFC
pax_myPartE = fvol_pax_myPartE()


pax_myPartE.check()
#pax_myPartE.exportBrep(f"{outFileName}.brep")
#pax_myPartE.exportIges(f"{outFileName}.igs")
#pax_myPartE.exportStep(f"{outFileName}.stp")
pax_myPartE.exportStl(f"{outFileName}.stl")

