# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartK"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartK_faceSide1_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartK_faceSide1_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartK_faceSide1_Fa0():
	FC000 = ctr_face_myPartK_faceSide1_Fa0_Ctr0()
	FC001 = ctr_face_myPartK_faceSide1_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceSide1_Fa1_Ctr0():
	P000 = App.Vector(-110.0000, 50.0000, 0)
	P001 = App.Vector(-140.0000, 50.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-140.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-110.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-110.0000, 50.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceSide1_Fa1():
	FC000 = ctr_face_myPartK_faceSide1_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceSide1_Fa2_Ctr0():
	P000 = App.Vector(140.0000, 50.0000, 0)
	P001 = App.Vector(110.0000, 50.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(110.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(140.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(140.0000, 50.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceSide1_Fa2():
	FC000 = ctr_face_myPartK_faceSide1_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartK_faceSide1():
	FA000 = face_myPartK_faceSide1_Fa0()
	FA001 = face_myPartK_faceSide1_Fa1()
	FA002 = face_myPartK_faceSide1_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartK_faceSide2_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartK_faceSide2_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartK_faceSide2_Fa0():
	FC000 = ctr_face_myPartK_faceSide2_Fa0_Ctr0()
	FC001 = ctr_face_myPartK_faceSide2_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceSide2_Fa1_Ctr0():
	P000 = App.Vector(-110.0000, 60.0000, 0)
	P001 = App.Vector(-140.0000, 60.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-140.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-110.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-110.0000, 60.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceSide2_Fa1():
	FC000 = ctr_face_myPartK_faceSide2_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceSide2_Fa2_Ctr0():
	P000 = App.Vector(140.0000, 60.0000, 0)
	P001 = App.Vector(110.0000, 60.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(110.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(140.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(140.0000, 60.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceSide2_Fa2():
	FC000 = ctr_face_myPartK_faceSide2_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartK_faceSide2():
	FA000 = face_myPartK_faceSide2_Fa0()
	FA001 = face_myPartK_faceSide2_Fa1()
	FA002 = face_myPartK_faceSide2_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartK_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-110.0000, 50.0000, 0)
	P001 = App.Vector(-140.0000, 50.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-140.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-110.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-110.0000, 50.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceTop_Fa0():
	FC000 = ctr_face_myPartK_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceTop_Fa1_Ctr0():
	P000 = App.Vector(140.0000, 50.0000, 0)
	P001 = App.Vector(110.0000, 50.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(110.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(140.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(140.0000, 50.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceTop_Fa1():
	FC000 = ctr_face_myPartK_faceTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceTop_Fa2_Ctr0():
	P000 = App.Vector(30.0000, 110.0000, 0)
	P001 = App.Vector(30.0000, 140.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.0000, 140.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(20.0000, 110.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 110.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceTop_Fa2():
	FC000 = ctr_face_myPartK_faceTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartK_faceTop_Fa3_Ctr0():
	P000 = App.Vector(30.0000, -140.0000, 0)
	P001 = App.Vector(30.0000, -110.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.0000, -110.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(20.0000, -140.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, -140.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartK_faceTop_Fa3():
	FC000 = ctr_face_myPartK_faceTop_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartK_faceTop():
	FA000 = face_myPartK_faceTop_Fa0()
	FA001 = face_myPartK_faceTop_Fa1()
	FA002 = face_myPartK_faceTop_Fa2()
	FA003 = face_myPartK_faceTop_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartAref1_faceSection_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartAref1_faceSection_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartAref1_faceSection_Fa0():
	FC000 = ctr_face_myPartAref1_faceSection_Fa0_Ctr0()
	FC001 = ctr_face_myPartAref1_faceSection_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartAref1_faceSection():
	FA000 = face_myPartAref1_faceSection_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartAref1_faceSide_Fa0_Ctr0():
	P000 = App.Vector(30.0000, 0.0000, 0)
	P001 = App.Vector(30.0000, 30.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(20.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartAref1_faceSide_Fa0():
	FC000 = ctr_face_myPartAref1_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartAref1_faceSide():
	FA000 = face_myPartAref1_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartAref1():
	FIG = myPartAref1_faceSection()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartAref1 = fex_subpax_myPartAref1()

pax_myPartAref1 = subpax_myPartAref1
def ctr_face_myPartAref2_faceSection_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartAref2_faceSection_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartAref2_faceSection_Fa0():
	FC000 = ctr_face_myPartAref2_faceSection_Fa0_Ctr0()
	FC001 = ctr_face_myPartAref2_faceSection_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartAref2_faceSection():
	FA000 = face_myPartAref2_faceSection_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartAref2_faceSide_Fa0_Ctr0():
	P000 = App.Vector(50.0000, 0.0000, 0)
	P001 = App.Vector(50.0000, 30.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(40.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(50.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartAref2_faceSide_Fa0():
	FC000 = ctr_face_myPartAref2_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartAref2_faceSide():
	FA000 = face_myPartAref2_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartAref2():
	FIG = myPartAref2_faceSection()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartAref2 = fex_subpax_myPartAref2()

pax_myPartAref2 = subpax_myPartAref2
def ctr_face_myPartD_faceTube1_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartD_faceTube1_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartD_faceTube1_Fa0():
	FC000 = ctr_face_myPartD_faceTube1_Fa0_Ctr0()
	FC001 = ctr_face_myPartD_faceTube1_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartD_faceTube1():
	FA000 = face_myPartD_faceTube1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartD_faceTube2_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartD_faceTube2_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartD_faceTube2_Fa0():
	FC000 = ctr_face_myPartD_faceTube2_Fa0_Ctr0()
	FC001 = ctr_face_myPartD_faceTube2_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartD_faceTube2():
	FA000 = face_myPartD_faceTube2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartD_faceTube1H_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartD_faceTube1H_Fa0():
	FC000 = ctr_face_myPartD_faceTube1H_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartD_faceTube1H():
	FA000 = face_myPartD_faceTube1H_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartD_faceTube2H_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartD_faceTube2H_Fa0():
	FC000 = ctr_face_myPartD_faceTube2H_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartD_faceTube2H():
	FA000 = face_myPartD_faceTube2H_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def myPartD_faceTop():
	rOneFig = undefined
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartD_tube1():
	FIG = myPartD_faceTube1()
	VEX = FIG.extrude(App.Vector(0, 0, 160))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -80.0000, 60.0000))
	return VFP
subpax_myPartD_tube1 = fex_subpax_myPartD_tube1()

def fex_subpax_myPartD_tube1H():
	FIG = myPartD_faceTube1H()
	VEX = FIG.extrude(App.Vector(0, 0, 160))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -80.0000, 60.0000))
	return VFP
subpax_myPartD_tube1H = fex_subpax_myPartD_tube1H()

def fex_subpax_myPartD_tube2():
	FIG = myPartD_faceTube2()
	VEX = FIG.extrude(App.Vector(0, 0, 160))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-80.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartD_tube2 = fex_subpax_myPartD_tube2()

def fex_subpax_myPartD_tube2H():
	FIG = myPartD_faceTube2H()
	VEX = FIG.extrude(App.Vector(0, 0, 160))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-80.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartD_tube2H = fex_subpax_myPartD_tube2H()

def fvol_ipax_myPartD_addi():
	V000 = subpax_myPartD_tube1
	V001 = V000.fuse(subpax_myPartD_tube2)
	VFC = V001.removeSplitter()
	return VFC
ipax_myPartD_addi = fvol_ipax_myPartD_addi()

def fvol_ipax_myPartD_subs():
	V000 = subpax_myPartD_tube1H
	V001 = V000.fuse(subpax_myPartD_tube2H)
	VFC = V001.removeSplitter()
	return VFC
ipax_myPartD_subs = fvol_ipax_myPartD_subs()

def fvol_pax_myPartD():
	V000 = ipax_myPartD_addi
	V001 = V000.cut(ipax_myPartD_subs)
	VFC = V001.removeSplitter()
	return VFC
pax_myPartD = fvol_pax_myPartD()

def finh_inpax_myPartK_A11():
	IVR1 = pax_myPartAref1.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, -140.0000, 30.0000))
	return IVF
inpax_myPartK_A11 = finh_inpax_myPartK_A11()

def finh_inpax_myPartK_A12():
	IVR1 = pax_myPartAref1.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 110.0000, 30.0000))
	return IVF
inpax_myPartK_A12 = finh_inpax_myPartK_A12()

def finh_inpax_myPartK_A21():
	IVR1 = pax_myPartAref2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(-140.0000, 0.0000, 0.0000))
	return IVF
inpax_myPartK_A21 = finh_inpax_myPartK_A21()

def finh_inpax_myPartK_A22():
	IVR1 = pax_myPartAref2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(110.0000, 0.0000, 0.0000))
	return IVF
inpax_myPartK_A22 = finh_inpax_myPartK_A22()

def finh_inpax_myPartK_cross():
	IVR1 = pax_myPartD.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_myPartK_cross = finh_inpax_myPartK_cross()

def fvol_pax_myPartK():
	V000 = inpax_myPartK_A11
	V001 = V000.fuse(inpax_myPartK_A12)
	V002 = V001.fuse(inpax_myPartK_A21)
	V003 = V002.fuse(inpax_myPartK_A22)
	V004 = V003.fuse(inpax_myPartK_cross)
	VFC = V004.removeSplitter()
	return VFC
pax_myPartK = fvol_pax_myPartK()


pax_myPartK.check()
#pax_myPartK.exportBrep(f"{outFileName}.brep")
#pax_myPartK.exportIges(f"{outFileName}.igs")
#pax_myPartK.exportStep(f"{outFileName}.stp")
pax_myPartK.exportStl(f"{outFileName}.stl")

