# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartU"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartU_faceSide_Fa0_Ctr0():
	P000 = App.Vector(30.0000, 80.0000, 0)
	P001 = App.Vector(30.0000, 120.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 120.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(25.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 80.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartU_faceSide_Fa0():
	FC000 = ctr_face_myPartU_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartU_faceSide_Fa1_Ctr0():
	P000 = App.Vector(15.0000, 0.0000, 0)
	P001 = App.Vector(15.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartU_faceSide_Fa1():
	FC000 = ctr_face_myPartU_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartU_faceSide_Fa2_Ctr0():
	P000 = App.Vector(15.0000, 160.0000, 0)
	P001 = App.Vector(15.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 160.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, 160.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartU_faceSide_Fa2():
	FC000 = ctr_face_myPartU_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartU_faceSide():
	FA000 = face_myPartU_faceSide_Fa0()
	FA001 = face_myPartU_faceSide_Fa1()
	FA002 = face_myPartU_faceSide_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartU_faceSection_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartU_faceSection_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartU_faceSection_Fa0():
	FC000 = ctr_face_myPartU_faceSection_Fa0_Ctr0()
	FC001 = ctr_face_myPartU_faceSection_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_myPartU_faceSection_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartU_faceSection_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartU_faceSection_Fa1():
	FC000 = ctr_face_myPartU_faceSection_Fa1_Ctr0()
	FC001 = ctr_face_myPartU_faceSection_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartU_faceSection():
	FA000 = face_myPartU_faceSection_Fa0()
	FA001 = face_myPartU_faceSection_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartAref1_faceSection_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartAref1_faceSection_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartAref1_faceSection_Fa0():
	FC000 = ctr_face_myPartAref1_faceSection_Fa0_Ctr0()
	FC001 = ctr_face_myPartAref1_faceSection_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartAref1_faceSection():
	FA000 = face_myPartAref1_faceSection_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartAref1_faceSide_Fa0_Ctr0():
	P000 = App.Vector(30.0000, 0.0000, 0)
	P001 = App.Vector(30.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(25.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartAref1_faceSide_Fa0():
	FC000 = ctr_face_myPartAref1_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartAref1_faceSide():
	FA000 = face_myPartAref1_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartAref1():
	FIG = myPartAref1_faceSection()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartAref1 = fex_subpax_myPartAref1()

pax_myPartAref1 = subpax_myPartAref1
def ctr_face_myPartAref2_faceSection_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartAref2_faceSection_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartAref2_faceSection_Fa0():
	FC000 = ctr_face_myPartAref2_faceSection_Fa0_Ctr0()
	FC001 = ctr_face_myPartAref2_faceSection_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartAref2_faceSection():
	FA000 = face_myPartAref2_faceSection_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartAref2_faceSide_Fa0_Ctr0():
	P000 = App.Vector(15.0000, 0.0000, 0)
	P001 = App.Vector(15.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartAref2_faceSide_Fa0():
	FC000 = ctr_face_myPartAref2_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartAref2_faceSide():
	FA000 = face_myPartAref2_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartAref2():
	FIG = myPartAref2_faceSection()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartAref2 = fex_subpax_myPartAref2()

pax_myPartAref2 = subpax_myPartAref2
def finh_inpax_myPartU_A1():
	IVR1 = pax_myPartAref1.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 80.0000))
	return IVF
inpax_myPartU_A1 = finh_inpax_myPartU_A1()

def finh_inpax_myPartU_A21():
	IVR1 = pax_myPartAref2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_myPartU_A21 = finh_inpax_myPartU_A21()

def finh_inpax_myPartU_A22():
	IVR1 = pax_myPartAref2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 160.0000))
	return IVF
inpax_myPartU_A22 = finh_inpax_myPartU_A22()

def fvol_pax_myPartU():
	V000 = inpax_myPartU_A1
	V001 = V000.fuse(inpax_myPartU_A21)
	V002 = V001.fuse(inpax_myPartU_A22)
	VFC = V002.removeSplitter()
	return VFC
pax_myPartU = fvol_pax_myPartU()


pax_myPartU.check()
#pax_myPartU.exportBrep(f"{outFileName}.brep")
#pax_myPartU.exportIges(f"{outFileName}.igs")
#pax_myPartU.exportStep(f"{outFileName}.stp")
pax_myPartU.exportStl(f"{outFileName}.stl")

