# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartN"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartN_face1_Fa0_Ctr0():
	P000 = App.Vector(20.5751, 1.7118, 0)
	P001 = App.Vector(24.2470, 5.1689, 0)
	P002 = App.Vector(26.1734, 9.8296, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(25.1707, 11.9397, 0)
	P004 = App.Vector(22.8514, 11.6596, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(15.3179, 6.5485, 0)
	P006 = App.Vector(6.6224, 3.8533, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(3.5355, 3.5355, 0)
	P008 = App.Vector(3.8533, 6.6224, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(6.6857, 15.5996, 0)
	P010 = App.Vector(12.0886, 23.3082, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(13.4657, 23.6046, 0)
	S005 = Part.LineSegment(P010, P011)
	P012 = App.Vector(14.5868, 26.8335, 0)
	P013 = App.Vector(11.2043, 26.3424, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(5.7503, 24.6236, 0)
	P015 = App.Vector(1.7118, 20.5751, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(0.0000, 19.6093, 0)
	P017 = App.Vector(-1.7118, 20.5751, 0)
	S008 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-5.1689, 24.2470, 0)
	P019 = App.Vector(-9.8296, 26.1734, 0)
	S009 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-11.9397, 25.1707, 0)
	P021 = App.Vector(-11.6596, 22.8514, 0)
	S010 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-6.5485, 15.3179, 0)
	P023 = App.Vector(-3.8533, 6.6224, 0)
	S011 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-3.5355, 3.5355, 0)
	P025 = App.Vector(-6.6224, 3.8533, 0)
	S012 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-15.5996, 6.6857, 0)
	P027 = App.Vector(-23.3082, 12.0886, 0)
	S013 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-23.6046, 13.4657, 0)
	S014 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-26.8335, 14.5868, 0)
	P030 = App.Vector(-26.3424, 11.2043, 0)
	S015 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-24.6236, 5.7503, 0)
	P032 = App.Vector(-20.5751, 1.7118, 0)
	S016 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(-19.6093, -0.0000, 0)
	P034 = App.Vector(-20.5751, -1.7118, 0)
	S017 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-24.2470, -5.1689, 0)
	P036 = App.Vector(-26.1734, -9.8296, 0)
	S018 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-25.1707, -11.9397, 0)
	P038 = App.Vector(-22.8514, -11.6596, 0)
	S019 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-15.3179, -6.5485, 0)
	P040 = App.Vector(-6.6224, -3.8533, 0)
	S020 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-3.5355, -3.5355, 0)
	P042 = App.Vector(-3.8533, -6.6224, 0)
	S021 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-6.6857, -15.5996, 0)
	P044 = App.Vector(-12.0886, -23.3082, 0)
	S022 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-13.4657, -23.6046, 0)
	S023 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-14.5868, -26.8335, 0)
	P047 = App.Vector(-11.2043, -26.3424, 0)
	S024 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-5.7503, -24.6236, 0)
	P049 = App.Vector(-1.7118, -20.5751, 0)
	S025 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(-0.0000, -19.6093, 0)
	P051 = App.Vector(1.7118, -20.5751, 0)
	S026 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(5.1689, -24.2470, 0)
	P053 = App.Vector(9.8296, -26.1734, 0)
	S027 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(11.9397, -25.1707, 0)
	P055 = App.Vector(11.6596, -22.8514, 0)
	S028 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(6.5485, -15.3179, 0)
	P057 = App.Vector(3.8533, -6.6224, 0)
	S029 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(3.5355, -3.5355, 0)
	P059 = App.Vector(6.6224, -3.8533, 0)
	S030 = Part.Arc(P057, P058, P059)
	P060 = App.Vector(15.5996, -6.6857, 0)
	P061 = App.Vector(23.3082, -12.0886, 0)
	S031 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(23.6046, -13.4657, 0)
	S032 = Part.LineSegment(P061, P062)
	P063 = App.Vector(26.8335, -14.5868, 0)
	P064 = App.Vector(26.3424, -11.2043, 0)
	S033 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(24.6236, -5.7503, 0)
	P066 = App.Vector(20.5751, -1.7118, 0)
	S034 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(19.6093, -0.0000, 0)
	P068 = App.Vector(20.5751, 1.7118, 0)
	S035 = Part.Arc(P066, P067, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartN_face1_Fa0():
	FC000 = ctr_face_myPartN_face1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartN_face1():
	FA000 = face_myPartN_face1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartN():
	FIG = myPartN_face1()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartN = fex_subpax_myPartN()

pax_myPartN = subpax_myPartN

pax_myPartN.check()
#pax_myPartN.exportBrep(f"{outFileName}.brep")
#pax_myPartN.exportIges(f"{outFileName}.igs")
#pax_myPartN.exportStep(f"{outFileName}.stp")
pax_myPartN.exportStl(f"{outFileName}.stl")

