# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartJ"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartJ_face1_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(890.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(897.0711, 2.9289, 0)
	P003 = App.Vector(900.0000, 10.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(900.0000, 560.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.0000, 560.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(2.9289, 557.0711, 0)
	P007 = App.Vector(0.0000, 550.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face1_Fa0_Ctr1():
	P000 = App.Vector(114.1421, 130.0000, 0)
	P001 = App.Vector(390.0000, 130.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(397.0711, 132.9289, 0)
	P003 = App.Vector(400.0000, 140.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(400.0000, 415.8579, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(400.0000, 430.0000, 0)
	P006 = App.Vector(385.8579, 430.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(110.0000, 430.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(102.9289, 427.0711, 0)
	P009 = App.Vector(100.0000, 420.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(100.0000, 144.1421, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(100.0000, 130.0000, 0)
	P012 = App.Vector(114.1421, 130.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face1_Fa0_Ctr2():
	P000 = App.Vector(500.0000, 130.0000, 0)
	P001 = App.Vector(800.0000, 130.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(650.0000, 430.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(500.0000, 130.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartJ_face1_Fa0():
	FC000 = ctr_face_myPartJ_face1_Fa0_Ctr0()
	FC001 = ctr_face_myPartJ_face1_Fa0_Ctr1()
	FC002 = ctr_face_myPartJ_face1_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def myPartJ_face1():
	FA000 = face_myPartJ_face1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartJ_face2_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(900.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(900.0000, 1000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face2_Fa0_Ctr1():
	P000 = App.Vector(100.0000, 200.0000, 0)
	P001 = App.Vector(200.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(159.7014, 361.1943, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(150.0000, 368.7689, 0)
	P004 = App.Vector(140.2986, 361.1943, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(100.0000, 200.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face2_Fa0_Ctr2():
	P000 = App.Vector(300.0000, 200.0000, 0)
	P001 = App.Vector(500.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(409.7014, 561.1943, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(400.0000, 568.7689, 0)
	P004 = App.Vector(390.2986, 561.1943, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(300.0000, 200.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face2_Fa0_Ctr3():
	P000 = App.Vector(600.0000, 200.0000, 0)
	P001 = App.Vector(800.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(719.4029, 522.3886, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(700.0000, 537.5379, 0)
	P004 = App.Vector(680.5971, 522.3886, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(600.0000, 200.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face2_Fa0_Ctr4():
	P000 = App.Vector(339.8638, 669.4622, 0)
	P001 = App.Vector(410.5745, 740.1729, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(268.0975, 825.6591, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(255.8815, 824.1552, 0)
	P004 = App.Vector(254.3776, 811.9392, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(339.8638, 669.4622, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face2_Fa0_Ctr5():
	P000 = App.Vector(598.4425, 740.1729, 0)
	P001 = App.Vector(669.1532, 669.4622, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(754.6393, 811.9392, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(753.1355, 824.1552, 0)
	P004 = App.Vector(740.9195, 825.6591, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(598.4425, 740.1729, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartJ_face2_Fa0():
	FC000 = ctr_face_myPartJ_face2_Fa0_Ctr0()
	FC001 = ctr_face_myPartJ_face2_Fa0_Ctr1()
	FC002 = ctr_face_myPartJ_face2_Fa0_Ctr2()
	FC003 = ctr_face_myPartJ_face2_Fa0_Ctr3()
	FC004 = ctr_face_myPartJ_face2_Fa0_Ctr4()
	FC005 = ctr_face_myPartJ_face2_Fa0_Ctr5()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005])
	rOneFace.check()
	return rOneFace

def myPartJ_face2():
	FA000 = face_myPartJ_face2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartJ_face3_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1000.0000, -0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1000.0000, 550.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(997.0711, 557.0711, 0)
	P004 = App.Vector(990.0000, 560.0000, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(0.0000, 560.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S004 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face3_Fa0_Ctr1():
	P000 = App.Vector(166.6667, 140.0000, 0)
	P001 = App.Vector(333.3333, 140.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(250.0000, 420.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(166.6667, 140.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face3_Fa0_Ctr2():
	P000 = App.Vector(583.3333, 420.0000, 0)
	P001 = App.Vector(416.6667, 420.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(500.0000, 140.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(583.3333, 420.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartJ_face3_Fa0_Ctr3():
	P000 = App.Vector(666.6667, 140.0000, 0)
	P001 = App.Vector(833.3333, 140.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(750.0000, 420.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(666.6667, 140.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartJ_face3_Fa0():
	FC000 = ctr_face_myPartJ_face3_Fa0_Ctr0()
	FC001 = ctr_face_myPartJ_face3_Fa0_Ctr1()
	FC002 = ctr_face_myPartJ_face3_Fa0_Ctr2()
	FC003 = ctr_face_myPartJ_face3_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def myPartJ_face3():
	FA000 = face_myPartJ_face3_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartJ_1():
	FIG = myPartJ_face1()
	VEX = FIG.extrude(App.Vector(0, 0, 1000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartJ_1 = fex_subpax_myPartJ_1()

def fex_subpax_myPartJ_2():
	FIG = myPartJ_face2()
	VEX = FIG.extrude(App.Vector(0, 0, 560))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1000.0000))
	return VFP
subpax_myPartJ_2 = fex_subpax_myPartJ_2()

def fex_subpax_myPartJ_3():
	FIG = myPartJ_face3()
	VEX = FIG.extrude(App.Vector(0, 0, 900))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1000.0000))
	return VFP
subpax_myPartJ_3 = fex_subpax_myPartJ_3()

def fvol_pax_myPartJ():
	V000 = subpax_myPartJ_1
	V001 = V000.common(subpax_myPartJ_2)
	V002 = V001.common(subpax_myPartJ_3)
	VFC = V002.removeSplitter()
	return VFC
pax_myPartJ = fvol_pax_myPartJ()


pax_myPartJ.check()
#pax_myPartJ.exportBrep(f"{outFileName}.brep")
#pax_myPartJ.exportIges(f"{outFileName}.igs")
#pax_myPartJ.exportStep(f"{outFileName}.stp")
pax_myPartJ.exportStl(f"{outFileName}.stl")

