# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartC"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartC_faceBodyCut_Fa0_Ctr0():
	P000 = App.Vector(-50.0000, 0.0000, 0)
	P001 = App.Vector(-50.0000, 100.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-20.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-20.0000, 180.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-50.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartC_faceBodyCut_Fa0():
	FC000 = ctr_face_myPartC_faceBodyCut_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartC_faceBodyCut():
	FA000 = face_myPartC_faceBodyCut_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartC_faceBodySlant_Fa0_Ctr0():
	P000 = App.Vector(-50.0000, 0.0000, 0)
	P001 = App.Vector(-50.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(50.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-50.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartC_faceBodySlant_Fa0():
	FC000 = ctr_face_myPartC_faceBodySlant_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartC_faceBodySlant():
	FA000 = face_myPartC_faceBodySlant_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartC_faceBodyHollow_Fa0_Ctr0():
	P000 = App.Vector(-50.0000, 0.0000, 0)
	P001 = App.Vector(-20.0000, 180.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-20.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 200.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-50.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartC_faceBodyHollow_Fa0():
	FC000 = ctr_face_myPartC_faceBodyHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartC_faceBodyHollow():
	FA000 = face_myPartC_faceBodyHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartC_faceChimney_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 75.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartC_faceChimney_Fa0():
	FC000 = ctr_face_myPartC_faceChimney_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartC_faceChimney():
	FA000 = face_myPartC_faceChimney_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartC_faceChimneyHollow_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 75.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_myPartC_faceChimneyHollow_Fa0():
	FC000 = ctr_face_myPartC_faceChimneyHollow_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartC_faceChimneyHollow():
	FA000 = face_myPartC_faceChimneyHollow_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartC_bodyRaw():
	FIG = myPartC_faceBodyCut()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartC_bodyRaw = fex_subpax_myPartC_bodyRaw()

def fex_subpax_myPartC_bodySlant():
	FIG = myPartC_faceBodySlant()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(50.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartC_bodySlant = fex_subpax_myPartC_bodySlant()

def fex_subpax_myPartC_bodyH():
	FIG = myPartC_faceBodyHollow()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartC_bodyH = fex_subpax_myPartC_bodyH()

def fex_subpax_myPartC_chimney():
	FIG = myPartC_faceChimney()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartC_chimney = fex_subpax_myPartC_chimney()

def fex_subpax_myPartC_chimneyH():
	FIG = myPartC_faceChimneyHollow()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartC_chimneyH = fex_subpax_myPartC_chimneyH()

def fvol_ipax_myPartC_body1():
	V000 = subpax_myPartC_bodyRaw
	V001 = V000.common(subpax_myPartC_bodySlant)
	VFC = V001.removeSplitter()
	return VFC
ipax_myPartC_body1 = fvol_ipax_myPartC_body1()

def fvol_ipax_myPartC_body2():
	V000 = ipax_myPartC_body1
	V001 = V000.fuse(subpax_myPartC_chimney)
	VFC = V001.removeSplitter()
	return VFC
ipax_myPartC_body2 = fvol_ipax_myPartC_body2()

def fvol_ipax_myPartC_hollow():
	V000 = subpax_myPartC_bodyH
	V001 = V000.fuse(subpax_myPartC_chimneyH)
	VFC = V001.removeSplitter()
	return VFC
ipax_myPartC_hollow = fvol_ipax_myPartC_hollow()

def fvol_ipax_myPartC_body3():
	V000 = ipax_myPartC_body2
	V001 = V000.cut(ipax_myPartC_hollow)
	VFC = V001.removeSplitter()
	return VFC
ipax_myPartC_body3 = fvol_ipax_myPartC_body3()

pax_myPartC = ipax_myPartC_body3

pax_myPartC.check()
#pax_myPartC.exportBrep(f"{outFileName}.brep")
#pax_myPartC.exportIges(f"{outFileName}.igs")
#pax_myPartC.exportStep(f"{outFileName}.stp")
pax_myPartC.exportStl(f"{outFileName}.stl")

