# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartH"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartH_faceCircle_Fa0_Ctr0():
	P000 = App.Vector(298.4000, 0.0000, 0)
	P001 = App.Vector(298.4000, -100.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(328.4000, -40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(358.4000, -100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(358.4000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(445.0025, 50.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(378.0410, 45.9808, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(415.0025, 101.9615, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(328.4000, 51.9615, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(241.7975, 101.9615, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(278.7590, 45.9808, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(211.7975, 50.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(298.4000, 0.0000, 0)
	S011 = Part.LineSegment(P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartH_faceCircle_Fa0():
	FC000 = ctr_face_myPartH_faceCircle_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartH_faceCircle():
	FA000 = face_myPartH_faceCircle_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartH_faceLine_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, -10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, -110.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(30.0000, -50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(60.0000, -110.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(60.0000, -10.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(100.0000, -10.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(100.0000, -130.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(136.0000, -58.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(172.0000, -130.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(172.0000, -10.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(212.0000, -10.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(212.0000, -154.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(255.2000, -67.6000, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(298.4000, -154.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(298.4000, -10.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(298.4000, 0.0000, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 0.0000, 0)
	S016 = Part.LineSegment(P016, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartH_faceLine_Fa0():
	FC000 = ctr_face_myPartH_faceLine_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartH_faceLine():
	FA000 = face_myPartH_faceLine_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartH_circle():
	FIG = myPartH_faceCircle()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartH_circle = fex_subpax_myPartH_circle()

def fex_subpax_myPartH_line():
	FIG = myPartH_faceLine()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartH_line = fex_subpax_myPartH_line()

def fvol_pax_myPartH():
	V000 = subpax_myPartH_circle
	V001 = V000.fuse(subpax_myPartH_line)
	VFC = V001.removeSplitter()
	return VFC
pax_myPartH = fvol_pax_myPartH()


pax_myPartH.check()
#pax_myPartH.exportBrep(f"{outFileName}.brep")
#pax_myPartH.exportIges(f"{outFileName}.igs")
#pax_myPartH.exportStep(f"{outFileName}.stp")
pax_myPartH.exportStl(f"{outFileName}.stl")

