# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartS"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartS_flat_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.2076, -10.6817, 0)
	P002 = App.Vector(14.7359, -15.2595, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(72.9331, -28.1180, 0)
	P004 = App.Vector(121.5290, -62.6245, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(126.8059, -63.1183, 0)
	P006 = App.Vector(127.9408, -57.9412, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(105.2662, -24.3174, 0)
	P008 = App.Vector(77.2330, 4.9885, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(60.0627, 15.4296, 0)
	P010 = App.Vector(40.3430, 19.2989, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(23.6866, 17.6536, 0)
	P012 = App.Vector(7.8539, 12.2255, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.1904, 7.2283, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa0():
	FC000 = ctr_face_myPartS_flat_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa1_Ctr0():
	P000 = App.Vector(0.0000, -120.0000, 0)
	P001 = App.Vector(3.4003, -130.4032, 0)
	P002 = App.Vector(13.1608, -135.3549, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(71.3734, -147.3737, 0)
	P004 = App.Vector(124.7083, -173.6140, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(130.0165, -172.8015, 0)
	P006 = App.Vector(129.7326, -167.4390, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(99.5640, -140.3185, 0)
	P008 = App.Vector(66.8510, -116.3285, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(52.3101, -109.1882, 0)
	P010 = App.Vector(36.4444, -105.9168, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.6248, -106.4296, 0)
	P012 = App.Vector(7.2847, -110.2040, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.2270, -114.0494, 0)
	P014 = App.Vector(0.0000, -120.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa1():
	FC000 = ctr_face_myPartS_flat_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa2_Ctr0():
	P000 = App.Vector(0.0000, -240.0000, 0)
	P001 = App.Vector(2.6414, -250.0683, 0)
	P002 = App.Vector(11.6284, -255.3199, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(68.4462, -268.4668, 0)
	P004 = App.Vector(121.9345, -291.7072, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(127.1731, -290.4347, 0)
	P006 = App.Vector(126.3868, -285.1013, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(94.0857, -260.4835, 0)
	P008 = App.Vector(60.1973, -238.1010, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(48.1097, -232.3142, 0)
	P010 = App.Vector(35.0911, -229.1340, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.0571, -228.7546, 0)
	P012 = App.Vector(7.2738, -231.4223, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.3869, -234.6512, 0)
	P014 = App.Vector(0.0000, -240.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa2():
	FC000 = ctr_face_myPartS_flat_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa3_Ctr0():
	P000 = App.Vector(0.0000, -360.0000, 0)
	P001 = App.Vector(1.9346, -369.6818, 0)
	P002 = App.Vector(10.1487, -375.1599, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(64.5344, -389.9255, 0)
	P004 = App.Vector(116.3439, -412.0973, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(121.5530, -410.6722, 0)
	P006 = App.Vector(120.5948, -405.3573, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(88.1764, -381.8823, 0)
	P008 = App.Vector(54.6411, -360.0323, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(44.6834, -355.0553, 0)
	P010 = App.Vector(33.9997, -351.9274, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.6179, -350.7423, 0)
	P012 = App.Vector(7.2902, -352.4301, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.5339, -355.1449, 0)
	P014 = App.Vector(0.0000, -360.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa3():
	FC000 = ctr_face_myPartS_flat_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa4_Ctr0():
	P000 = App.Vector(0.0000, -480.0000, 0)
	P001 = App.Vector(1.2834, -489.2489, 0)
	P002 = App.Vector(8.7308, -494.8813, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(59.7584, -511.1994, 0)
	P004 = App.Vector(108.6996, -532.9906, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(113.9091, -531.5618, 0)
	P006 = App.Vector(112.9449, -526.2467, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(81.7453, -503.4401, 0)
	P008 = App.Vector(49.7085, -481.8253, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(41.6370, -477.4709, 0)
	P010 = App.Vector(32.9750, -474.4576, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.1945, -472.5328, 0)
	P012 = App.Vector(7.2941, -473.3231, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.6604, -475.5837, 0)
	P014 = App.Vector(0.0000, -480.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa4():
	FC000 = ctr_face_myPartS_flat_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa5_Ctr0():
	P000 = App.Vector(0.0000, -600.0000, 0)
	P001 = App.Vector(0.6906, -608.7746, 0)
	P002 = App.Vector(7.3835, -614.4908, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(54.2050, -631.9884, 0)
	P004 = App.Vector(99.3301, -653.4862, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(104.5546, -652.1408, 0)
	P006 = App.Vector(103.6871, -646.8160, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(74.8187, -624.6814, 0)
	P008 = App.Vector(45.2971, -603.4258, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(38.8687, -599.6136, 0)
	P010 = App.Vector(31.9500, -596.7869, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(19.7494, -594.1793, 0)
	P012 = App.Vector(7.2732, -594.1372, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.7647, -595.9870, 0)
	P014 = App.Vector(0.0000, -600.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa5():
	FC000 = ctr_face_myPartS_flat_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa6_Ctr0():
	P000 = App.Vector(0.0000, -720.0000, 0)
	P001 = App.Vector(0.1587, -728.2644, 0)
	P002 = App.Vector(6.1147, -733.9961, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(47.9626, -752.0873, 0)
	P004 = App.Vector(88.4616, -773.0244, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(93.7033, -771.8216, 0)
	P006 = App.Vector(93.0103, -766.4885, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(67.4991, -745.3658, 0)
	P008 = App.Vector(41.4571, -724.9012, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(36.3849, -721.5538, 0)
	P010 = App.Vector(30.8956, -718.9464, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(19.2668, -715.7080, 0)
	P012 = App.Vector(7.2233, -714.8901, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.8470, -716.3641, 0)
	P014 = App.Vector(0.0000, -720.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa6():
	FC000 = ctr_face_myPartS_flat_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa7_Ctr0():
	P000 = App.Vector(0.0000, -840.0000, 0)
	P001 = App.Vector(-0.3102, -847.7240, 0)
	P002 = App.Vector(4.9321, -853.4050, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(41.1290, -871.3367, 0)
	P004 = App.Vector(76.3007, -891.2040, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(81.5493, -890.1923, 0)
	P006 = App.Vector(81.1058, -884.8655, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(59.9326, -865.3779, 0)
	P008 = App.Vector(38.2969, -846.4052, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(34.2353, -843.3867, 0)
	P010 = App.Vector(29.7982, -840.9535, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.7402, -837.1333, 0)
	P012 = App.Vector(7.1430, -835.5912, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.9077, -836.7201, 0)
	P014 = App.Vector(0.0000, -840.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa7():
	FC000 = ctr_face_myPartS_flat_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa8_Ctr0():
	P000 = App.Vector(0.0000, -960.0000, 0)
	P001 = App.Vector(-0.7146, -967.1589, 0)
	P002 = App.Vector(3.8423, -972.7262, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(33.8136, -989.6055, 0)
	P004 = App.Vector(63.0598, -1007.7121, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(68.2867, -1006.9419, 0)
	P006 = App.Vector(68.1904, -1001.6595, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(52.2688, -984.6804, 0)
	P008 = App.Vector(35.8889, -968.1431, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(32.4603, -965.2232, 0)
	P010 = App.Vector(28.6526, -962.8186, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.1675, -958.4639, 0)
	P012 = App.Vector(7.0328, -956.2463, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.9478, -957.0578, 0)
	P014 = App.Vector(0.0000, -960.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa8():
	FC000 = ctr_face_myPartS_flat_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_myPartS_flat_Fa9_Ctr0():
	P000 = App.Vector(0.0000, -1080.0000, 0)
	P001 = App.Vector(-1.0531, -1086.5749, 0)
	P002 = App.Vector(2.8513, -1091.9687, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(26.1373, -1106.7830, 0)
	P004 = App.Vector(48.9660, -1122.2929, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(54.0976, -1121.8413, 0)
	P006 = App.Vector(54.5286, -1116.7080, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(44.6010, -1103.2850, 0)
	P008 = App.Vector(34.1194, -1090.2899, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(31.0183, -1087.1526, 0)
	P010 = App.Vector(27.4575, -1084.5486, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(17.5491, -1079.7049, 0)
	P012 = App.Vector(6.8936, -1076.8588, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.9681, -1077.3788, 0)
	P014 = App.Vector(0.0000, -1080.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_flat_Fa9():
	FC000 = ctr_face_myPartS_flat_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_flat():
	FA000 = face_myPartS_flat_Fa0()
	FA001 = face_myPartS_flat_Fa1()
	FA002 = face_myPartS_flat_Fa2()
	FA003 = face_myPartS_flat_Fa3()
	FA004 = face_myPartS_flat_Fa4()
	FA005 = face_myPartS_flat_Fa5()
	FA006 = face_myPartS_flat_Fa6()
	FA007 = face_myPartS_flat_Fa7()
	FA008 = face_myPartS_flat_Fa8()
	FA009 = face_myPartS_flat_Fa9()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009])
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.2076, -10.6817, 0)
	P002 = App.Vector(14.7359, -15.2595, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(72.9331, -28.1180, 0)
	P004 = App.Vector(121.5290, -62.6245, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(126.8059, -63.1183, 0)
	P006 = App.Vector(127.9408, -57.9412, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(105.2662, -24.3174, 0)
	P008 = App.Vector(77.2330, 4.9885, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(60.0627, 15.4296, 0)
	P010 = App.Vector(40.3430, 19.2989, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(23.6866, 17.6536, 0)
	P012 = App.Vector(7.8539, 12.2255, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.1904, 7.2283, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf00_Fa0():
	FC000 = ctr_face_myPartS_prf00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf00():
	FA000 = face_myPartS_prf00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.4003, -10.4032, 0)
	P002 = App.Vector(13.1608, -15.3549, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(71.3734, -27.3737, 0)
	P004 = App.Vector(124.7083, -53.6140, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(130.0165, -52.8015, 0)
	P006 = App.Vector(129.7326, -47.4390, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(99.5640, -20.3185, 0)
	P008 = App.Vector(66.8510, 3.6715, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(52.3101, 10.8118, 0)
	P010 = App.Vector(36.4444, 14.0832, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.6248, 13.5704, 0)
	P012 = App.Vector(7.2847, 9.7960, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.2270, 5.9506, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf01_Fa0():
	FC000 = ctr_face_myPartS_prf01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf01():
	FA000 = face_myPartS_prf01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(2.6414, -10.0683, 0)
	P002 = App.Vector(11.6284, -15.3199, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(68.4462, -28.4668, 0)
	P004 = App.Vector(121.9345, -51.7072, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(127.1731, -50.4347, 0)
	P006 = App.Vector(126.3868, -45.1013, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(94.0857, -20.4835, 0)
	P008 = App.Vector(60.1973, 1.8990, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(48.1097, 7.6858, 0)
	P010 = App.Vector(35.0911, 10.8660, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.0571, 11.2454, 0)
	P012 = App.Vector(7.2738, 8.5777, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.3869, 5.3488, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf02_Fa0():
	FC000 = ctr_face_myPartS_prf02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf02():
	FA000 = face_myPartS_prf02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1.9346, -9.6818, 0)
	P002 = App.Vector(10.1487, -15.1599, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(64.5344, -29.9255, 0)
	P004 = App.Vector(116.3439, -52.0973, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(121.5530, -50.6722, 0)
	P006 = App.Vector(120.5948, -45.3573, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(88.1764, -21.8823, 0)
	P008 = App.Vector(54.6411, -0.0323, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(44.6834, 4.9447, 0)
	P010 = App.Vector(33.9997, 8.0726, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.6179, 9.2577, 0)
	P012 = App.Vector(7.2902, 7.5699, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.5339, 4.8551, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf03_Fa0():
	FC000 = ctr_face_myPartS_prf03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf03():
	FA000 = face_myPartS_prf03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf04_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1.2834, -9.2489, 0)
	P002 = App.Vector(8.7308, -14.8813, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(59.7584, -31.1994, 0)
	P004 = App.Vector(108.6996, -52.9906, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(113.9091, -51.5618, 0)
	P006 = App.Vector(112.9449, -46.2467, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(81.7453, -23.4401, 0)
	P008 = App.Vector(49.7085, -1.8253, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(41.6370, 2.5291, 0)
	P010 = App.Vector(32.9750, 5.5424, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.1945, 7.4672, 0)
	P012 = App.Vector(7.2941, 6.6769, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.6604, 4.4163, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf04_Fa0():
	FC000 = ctr_face_myPartS_prf04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf04():
	FA000 = face_myPartS_prf04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf05_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.6906, -8.7746, 0)
	P002 = App.Vector(7.3835, -14.4908, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(54.2050, -31.9884, 0)
	P004 = App.Vector(99.3301, -53.4862, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(104.5546, -52.1408, 0)
	P006 = App.Vector(103.6871, -46.8160, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(74.8187, -24.6814, 0)
	P008 = App.Vector(45.2971, -3.4258, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(38.8687, 0.3864, 0)
	P010 = App.Vector(31.9500, 3.2131, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(19.7494, 5.8207, 0)
	P012 = App.Vector(7.2732, 5.8628, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.7647, 4.0130, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf05_Fa0():
	FC000 = ctr_face_myPartS_prf05_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf05():
	FA000 = face_myPartS_prf05_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf06_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.1587, -8.2644, 0)
	P002 = App.Vector(6.1147, -13.9961, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(47.9626, -32.0873, 0)
	P004 = App.Vector(88.4616, -53.0244, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(93.7033, -51.8216, 0)
	P006 = App.Vector(93.0103, -46.4885, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(67.4991, -25.3658, 0)
	P008 = App.Vector(41.4571, -4.9012, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(36.3849, -1.5538, 0)
	P010 = App.Vector(30.8956, 1.0536, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(19.2668, 4.2920, 0)
	P012 = App.Vector(7.2233, 5.1099, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.8470, 3.6359, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf06_Fa0():
	FC000 = ctr_face_myPartS_prf06_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf06():
	FA000 = face_myPartS_prf06_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf07_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-0.3102, -7.7240, 0)
	P002 = App.Vector(4.9321, -13.4050, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(41.1290, -31.3367, 0)
	P004 = App.Vector(76.3007, -51.2040, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(81.5493, -50.1923, 0)
	P006 = App.Vector(81.1058, -44.8655, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(59.9326, -25.3779, 0)
	P008 = App.Vector(38.2969, -6.4052, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(34.2353, -3.3867, 0)
	P010 = App.Vector(29.7982, -0.9535, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.7402, 2.8667, 0)
	P012 = App.Vector(7.1430, 4.4088, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.9077, 3.2799, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf07_Fa0():
	FC000 = ctr_face_myPartS_prf07_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf07():
	FA000 = face_myPartS_prf07_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf08_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-0.7146, -7.1589, 0)
	P002 = App.Vector(3.8423, -12.7262, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(33.8136, -29.6055, 0)
	P004 = App.Vector(63.0598, -47.7121, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(68.2867, -46.9419, 0)
	P006 = App.Vector(68.1904, -41.6595, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(52.2688, -24.6804, 0)
	P008 = App.Vector(35.8889, -8.1431, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(32.4603, -5.2232, 0)
	P010 = App.Vector(28.6526, -2.8186, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(18.1675, 1.5361, 0)
	P012 = App.Vector(7.0328, 3.7537, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.9478, 2.9422, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf08_Fa0():
	FC000 = ctr_face_myPartS_prf08_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf08():
	FA000 = face_myPartS_prf08_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_myPartS_prf09_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(-1.0531, -6.5749, 0)
	P002 = App.Vector(2.8513, -11.9687, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(26.1373, -26.7830, 0)
	P004 = App.Vector(48.9660, -42.2929, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(54.0976, -41.8413, 0)
	P006 = App.Vector(54.5286, -36.7080, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(44.6010, -23.2850, 0)
	P008 = App.Vector(34.1194, -10.2899, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(31.0183, -7.1526, 0)
	P010 = App.Vector(27.4575, -4.5486, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(17.5491, 0.2951, 0)
	P012 = App.Vector(6.8936, 3.1412, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(2.9681, 2.6212, 0)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S006 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartS_prf09_Fa0():
	FC000 = ctr_face_myPartS_prf09_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartS_prf09():
	FA000 = face_myPartS_prf09_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartS_prf00():
	FIG = myPartS_prf00()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartS_prf00 = fex_subpax_myPartS_prf00()

def fex_subpax_myPartS_prf01():
	FIG = myPartS_prf01()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_myPartS_prf01 = fex_subpax_myPartS_prf01()

def fex_subpax_myPartS_prf02():
	FIG = myPartS_prf02()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 40.0000))
	return VFP
subpax_myPartS_prf02 = fex_subpax_myPartS_prf02()

def fex_subpax_myPartS_prf03():
	FIG = myPartS_prf03()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 60.0000))
	return VFP
subpax_myPartS_prf03 = fex_subpax_myPartS_prf03()

def fex_subpax_myPartS_prf04():
	FIG = myPartS_prf04()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 80.0000))
	return VFP
subpax_myPartS_prf04 = fex_subpax_myPartS_prf04()

def fex_subpax_myPartS_prf05():
	FIG = myPartS_prf05()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 100.0000))
	return VFP
subpax_myPartS_prf05 = fex_subpax_myPartS_prf05()

def fex_subpax_myPartS_prf06():
	FIG = myPartS_prf06()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 120.0000))
	return VFP
subpax_myPartS_prf06 = fex_subpax_myPartS_prf06()

def fex_subpax_myPartS_prf07():
	FIG = myPartS_prf07()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 140.0000))
	return VFP
subpax_myPartS_prf07 = fex_subpax_myPartS_prf07()

def fex_subpax_myPartS_prf08():
	FIG = myPartS_prf08()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 160.0000))
	return VFP
subpax_myPartS_prf08 = fex_subpax_myPartS_prf08()

def fex_subpax_myPartS_prf09():
	FIG = myPartS_prf09()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 180.0000))
	return VFP
subpax_myPartS_prf09 = fex_subpax_myPartS_prf09()

def fvol_pax_myPartS():
	V000 = subpax_myPartS_prf00
	V001 = V000.fuse(subpax_myPartS_prf01)
	V002 = V001.fuse(subpax_myPartS_prf02)
	V003 = V002.fuse(subpax_myPartS_prf03)
	V004 = V003.fuse(subpax_myPartS_prf04)
	V005 = V004.fuse(subpax_myPartS_prf05)
	V006 = V005.fuse(subpax_myPartS_prf06)
	V007 = V006.fuse(subpax_myPartS_prf07)
	V008 = V007.fuse(subpax_myPartS_prf08)
	V009 = V008.fuse(subpax_myPartS_prf09)
	VFC = V009.removeSplitter()
	return VFC
pax_myPartS = fvol_pax_myPartS()


pax_myPartS.check()
#pax_myPartS.exportBrep(f"{outFileName}.brep")
#pax_myPartS.exportIges(f"{outFileName}.igs")
#pax_myPartS.exportStep(f"{outFileName}.stp")
pax_myPartS.exportStl(f"{outFileName}.stl")

