# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartO"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartO_face1_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(40.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(44.0192, 15.0000, 0)
	P003 = App.Vector(40.0000, 30.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(31.5470, 38.4530, 0)
	P005 = App.Vector(20.0000, 41.5470, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(8.4530, 38.4530, 0)
	P007 = App.Vector(0.0000, 30.0000, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-4.0192, 15.0000, 0)
	P009 = App.Vector(0.0000, 0.0000, 0)
	S004 = Part.Arc(P007, P008, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartO_face1_Fa0():
	FC000 = ctr_face_myPartO_face1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartO_face1():
	FA000 = face_myPartO_face1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartO():
	FIG = myPartO_face1()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartO = fex_subpax_myPartO()

pax_myPartO = subpax_myPartO

pax_myPartO.check()
#pax_myPartO.exportBrep(f"{outFileName}.brep")
#pax_myPartO.exportIges(f"{outFileName}.igs")
#pax_myPartO.exportStep(f"{outFileName}.stp")
pax_myPartO.exportStl(f"{outFileName}.stl")

