# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartI"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartI_face2_Fa0_Ctr0():
	P000 = App.Vector(0.0000, -0.0000, 0)
	P001 = App.Vector(180.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(180.0000, 70.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(177.0711, 77.0711, 0)
	P004 = App.Vector(170.0000, 80.0000, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(0.0000, 80.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, -0.0000, 0)
	S004 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartI_face2_Fa0_Ctr1():
	P000 = App.Vector(30.0000, 20.0000, 0)
	P001 = App.Vector(60.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(45.0000, 60.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(30.0000, 20.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartI_face2_Fa0_Ctr2():
	P000 = App.Vector(105.0000, 60.0000, 0)
	P001 = App.Vector(75.0000, 60.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(90.0000, 20.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(105.0000, 60.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartI_face2_Fa0_Ctr3():
	P000 = App.Vector(120.0000, 20.0000, 0)
	P001 = App.Vector(150.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(135.0000, 60.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(120.0000, 20.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartI_face2_Fa0():
	FC000 = ctr_face_myPartI_face2_Fa0_Ctr0()
	FC001 = ctr_face_myPartI_face2_Fa0_Ctr1()
	FC002 = ctr_face_myPartI_face2_Fa0_Ctr2()
	FC003 = ctr_face_myPartI_face2_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def myPartI_face2():
	FA000 = face_myPartI_face2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartI_2():
	FIG = myPartI_face2()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartI_2 = fex_subpax_myPartI_2()

pax_myPartI = subpax_myPartI_2

pax_myPartI.check()
#pax_myPartI.exportBrep(f"{outFileName}.brep")
#pax_myPartI.exportIges(f"{outFileName}.igs")
#pax_myPartI.exportStep(f"{outFileName}.stp")
pax_myPartI.exportStl(f"{outFileName}.stl")

