# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartQ"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartQ_face1_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_myPartQ_face1_Fa0_Ctr1():
	P000 = App.Vector(13.5858, 1.4142, 0)
	P001 = App.Vector(1.4142, 13.5858, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.0000, 14.1716, 0)
	P003 = App.Vector(-1.4142, 13.5858, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-13.5858, 1.4142, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-14.1716, 0.0000, 0)
	P006 = App.Vector(-13.5858, -1.4142, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-1.4142, -13.5858, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(0.0000, -14.1716, 0)
	P009 = App.Vector(1.4142, -13.5858, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(13.5858, -1.4142, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(14.1716, -0.0000, 0)
	P012 = App.Vector(13.5858, 1.4142, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartQ_face1_Fa0():
	FC000 = ctr_face_myPartQ_face1_Fa0_Ctr0()
	FC001 = ctr_face_myPartQ_face1_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def myPartQ_face1():
	FA000 = face_myPartQ_face1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartQ():
	FIG = myPartQ_face1()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartQ = fex_subpax_myPartQ()

pax_myPartQ = subpax_myPartQ

pax_myPartQ.check()
#pax_myPartQ.exportBrep(f"{outFileName}.brep")
#pax_myPartQ.exportIges(f"{outFileName}.igs")
#pax_myPartQ.exportStep(f"{outFileName}.stp")
pax_myPartQ.exportStl(f"{outFileName}.stl")

