# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartL"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartL_face1_Fa0_Ctr0():
	P000 = App.Vector(24.5000, 0.0000, 0)
	P001 = App.Vector(30.2603, 8.7500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(13.7886, 13.7886, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(8.7500, 30.2603, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 24.5000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-8.7500, 30.2603, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-13.7886, 13.7886, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-30.2603, 8.7500, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-24.5000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-30.2603, -8.7500, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-13.7886, -13.7886, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-8.7500, -30.2603, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(-0.0000, -24.5000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(8.7500, -30.2603, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(13.7886, -13.7886, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(30.2603, -8.7500, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(24.5000, -0.0000, 0)
	S015 = Part.LineSegment(P015, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartL_face1_Fa0():
	FC000 = ctr_face_myPartL_face1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def myPartL_face1():
	FA000 = face_myPartL_face1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartL():
	FIG = myPartL_face1()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartL = fex_subpax_myPartL()

pax_myPartL = subpax_myPartL

pax_myPartL.check()
#pax_myPartL.exportBrep(f"{outFileName}.brep")
#pax_myPartL.exportIges(f"{outFileName}.igs")
#pax_myPartL.exportStep(f"{outFileName}.stp")
pax_myPartL.exportStl(f"{outFileName}.stl")

