# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "myPartG"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_myPartG_faceTransforms_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(900.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(900.0000, 1000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartG_faceTransforms_Fa0_Ctr1():
	P000 = App.Vector(100.0000, 200.0000, 0)
	P001 = App.Vector(200.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(159.7014, 361.1943, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(150.0000, 368.7689, 0)
	P004 = App.Vector(140.2986, 361.1943, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(100.0000, 200.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartG_faceTransforms_Fa0_Ctr2():
	P000 = App.Vector(300.0000, 200.0000, 0)
	P001 = App.Vector(500.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(409.7014, 561.1943, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(400.0000, 568.7689, 0)
	P004 = App.Vector(390.2986, 561.1943, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(300.0000, 200.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartG_faceTransforms_Fa0_Ctr3():
	P000 = App.Vector(600.0000, 200.0000, 0)
	P001 = App.Vector(800.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(719.4029, 522.3886, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(700.0000, 537.5379, 0)
	P004 = App.Vector(680.5971, 522.3886, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(600.0000, 200.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartG_faceTransforms_Fa0_Ctr4():
	P000 = App.Vector(339.8638, 669.4622, 0)
	P001 = App.Vector(410.5745, 740.1729, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(268.0975, 825.6591, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(255.8815, 824.1552, 0)
	P004 = App.Vector(254.3776, 811.9392, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(339.8638, 669.4622, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_myPartG_faceTransforms_Fa0_Ctr5():
	P000 = App.Vector(598.4425, 740.1729, 0)
	P001 = App.Vector(669.1532, 669.4622, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(754.6393, 811.9392, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(753.1355, 824.1552, 0)
	P004 = App.Vector(740.9195, 825.6591, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(598.4425, 740.1729, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_myPartG_faceTransforms_Fa0():
	FC000 = ctr_face_myPartG_faceTransforms_Fa0_Ctr0()
	FC001 = ctr_face_myPartG_faceTransforms_Fa0_Ctr1()
	FC002 = ctr_face_myPartG_faceTransforms_Fa0_Ctr2()
	FC003 = ctr_face_myPartG_faceTransforms_Fa0_Ctr3()
	FC004 = ctr_face_myPartG_faceTransforms_Fa0_Ctr4()
	FC005 = ctr_face_myPartG_faceTransforms_Fa0_Ctr5()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005])
	rOneFace.check()
	return rOneFace

def myPartG_faceTransforms():
	FA000 = face_myPartG_faceTransforms_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_myPartG_tf():
	FIG = myPartG_faceTransforms()
	VEX = FIG.extrude(App.Vector(0, 0, undefined))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_myPartG_tf = fex_subpax_myPartG_tf()

pax_myPartG = subpax_myPartG_tf

pax_myPartG.check()
#pax_myPartG.exportBrep(f"{outFileName}.brep")
#pax_myPartG.exportIges(f"{outFileName}.igs")
#pax_myPartG.exportStep(f"{outFileName}.stp")
pax_myPartG.exportStl(f"{outFileName}.stl")

